create extension if not exists pgcrypto with schema extensions;

create table public.weather_stations (
  id uuid primary key default gen_random_uuid(),
  station_code text unique not null check (station_code ~ '^[A-Z0-9_]{3,32}$'),
  name text not null check (char_length(name) between 1 and 120),
  location_name text,
  latitude double precision check (latitude between -90 and 90),
  longitude double precision check (longitude between -180 and 180),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.weather_readings (
  id bigint generated by default as identity primary key,
  station_id uuid not null references public.weather_stations(id) on delete cascade,
  temperature_c real not null check (temperature_c between -40 and 85),
  humidity_percent real not null check (humidity_percent between 0 and 100),
  pressure_hpa real not null check (pressure_hpa between 300 and 1100),
  bmp_temperature_c real check (bmp_temperature_c between -40 and 85),
  altitude_m real check (altitude_m between -500 and 10000),
  signal_rssi smallint check (signal_rssi between 0 and 31 or signal_rssi = 99),
  recorded_at timestamptz not null default now(),
  received_at timestamptz not null default now()
);

create index weather_readings_station_recorded_idx
  on public.weather_readings (station_id, recorded_at desc);
create index weather_readings_received_idx
  on public.weather_readings (received_at desc);

alter table public.weather_stations enable row level security;
alter table public.weather_readings enable row level security;

revoke all on public.weather_stations from anon, authenticated;
revoke all on public.weather_readings from anon, authenticated;
grant select on public.weather_stations to anon, authenticated;
grant select on public.weather_readings to anon, authenticated;

create policy "Public can read active weather stations"
  on public.weather_stations for select to anon, authenticated
  using (is_active = true);

create policy "Public can read active station measurements"
  on public.weather_readings for select to anon, authenticated
  using (exists (
    select 1 from public.weather_stations station
    where station.id = station_id and station.is_active = true
  ));

insert into public.weather_stations (station_code, name, location_name)
values ('WS_ABU_001', 'Abuja Weather Station 001', 'Abuja, Nigeria')
on conflict (station_code) do update
set name = excluded.name, location_name = excluded.location_name, updated_at = now();

